Repository pranavgoel29/CPP-Programs, pull requests merged in 2022-10, with the labels that each got.

#4 program to find fibonacci series using recursion
  First PR/fibonacci.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#5 CPP program to find the majority element uploaded
  First PR/majority_element.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#7 Cpp program for intersection between two arrays
  intersection_between_two_arrays.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#10 Create Sort-0,1.cpp
  Sort-0,1.cpp
Labels: hacktoberfest

#34 If Else Programme First PR
  First PR/if_else.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#35 Switch statement programme
  First PR/switch_statement.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#36 Do While Loop
  First PR/do_while_loop.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#37 Function
  First PR/function.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted
